### ISSUE TITLE
Reword "Requires Manual Resume When Stopped"

### ISSUE THREAD

**Issue by ngbrown** [openpilot-community/openpilotdb-app#12]
The capability "Requires Manual Resume When Stopped" is actually a disadvantage for a stock system and would be eliminated by OpenPilot.

To continue using a green check-mark, which generally mean "good", the item should be re-worded to a positive like "Can resume from stop without manual button press".

Also need a separate item "Can resume ACC from stop".  This is in contrast to a system where the driver would have to use the pedal to accelerate up to the minimum speed of the ACC system to then resume.

**Comment by jfrux** [comment]
Yeah, Its actually the capabilities and limitations tab now.

The purpose for this screen is to manage the capabilities and limitations at each tier.
Not so much to visualize.  At least not yet. It's more of a system to manage it for now until we get the actual generated visualization / “show” page.

The wording can be quickly changed though, so that’s not really an issue.

But it sounds more that your concern is with the color and what that signifies to our minds… truthfully it is just bright so we can clearly see which column is marked for building these lists out so we can generate docs later from it.

The most important thing for us at this point is to ensure we’re properly marking what the vehicles factory capabilities and limitations are versus what you gain by increasing difficulty tiers (aka, the amount of modifications required to get specific features).

I think we need to do more to tie the tiers to “mods” and “hardware” which is found through Guides.
We need to tie Guides / Hardware to those tiers in some way.

Thanks for helping us and I’d love to hear more responses so I can understand deeper your concerns.

:)

**Comment by jfrux** [comment]
Here is an example of my Pilot and what I kind of envisioned for it.
https://opc.ai/vehicles/2016-honda-pilot-e24fbo#!tab-capabilities
You'll see the 15 second timeout is specified.

**Comment by jfrux** [comment]
![image](https://user-images.githubusercontent.com/171077/45258181-9498e000-b381-11e8-8565-a87394774a22.png)

**Comment by jfrux** [comment]
I know the colors look positive and negative, but really its just to show included / excluded.
![image](https://user-images.githubusercontent.com/171077/45258199-f8bba400-b381-11e8-8ac5-d57158b40573.png)

**Comment by jfrux** [comment]
![image](https://user-images.githubusercontent.com/171077/45258508-ef810600-b386-11e8-8f17-d2696eb16733.png)

**Comment by jfrux** [comment]
So 3 states per box.

`not-applicable` doesn't show any text in the box at all, hover shows a "+"
`included` shows either a `tick`, or `value` and `value_type`
`excluded` always turns `disabled` styling with a `x`

Does that make sense?

**Comment by jfrux** [comment]
and the colors align with their difficulty colors in css

**Comment by jfrux** [comment]
Just deployed a couple if improvements to the React component for that button as well as style cleanup to hopefully make it clearer.

We do need more explanation behind what each of the wordings mean.  But again, this was originally designed to "build" the capabilities list, then we would elaborate on what each thing means in the docs that would be generated from the data.

It might be that we end up having this be a show/edit screen, where the default is a show-style screen and has more info about each tier, and what each feature means.

Just not a lot of room to put a lot of extra text with the data entry screen.

**Comment by ngbrown** [comment]
Thanks.
